version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: futanalysis_postgres
    restart: always
    environment:
      POSTGRES_DB: futanalysis
      POSTGRES_USER: futanalysis
      POSTGRES_PASSWORD: futanalysis
    ports:
      - "5432:5432"
    volumes:
      - futanalysis_pgdata:/var/lib/postgresql/data

volumes:
  futanalysis_pgdata: